# Generated by Django 5.2.6 on 2025-09-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('stock', models.IntegerField(default=0, max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
