# Generated by Django 5.2.6 on 2025-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('supplement', 'Supplement'), ('misc', 'Misc'), ('merch', 'Merch'), ('player', 'Player')], default='misc', max_length=25),
        ),
    ]
