# Generated by Django 5.2.6 on 2025-10-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, default='https://cdn.nba.com/manage/2021/08/michael-jordan-looks.jpg'),
        ),
    ]
